### ISSUE TITLE
Bug report to my blog

### ISSUE THREAD

**Issue by bobbysmith007** [AccelerationNet/cl-csv#10]
I’m getting the error: “we are reading non quoted csv data and found a quote at 1″
no matter what I do. SBCL on windows xp (yeah, yeah, laugh all you want, tell my boss).
I know the data is quoted, I want it to be quoted, _quote_ is set correctly, so is _always-quote_ so why does it think it’s non quoted

**Comment by analyticd** [comment]
I got this error too. One of the columns that I have in my data can have the double quote as an inches specifier and this causes the error. How do  you overcome this? In this particular case, the column delimiter is #\Tab so you wouldn't expect it to give special meaning to a double quote anyway. Please advise.

**Comment by bobbysmith007** [comment]
This behaviour is controlled by `*quote-escape*` and `*escape-mode*` which defaults to `""`.  If you can upload a minimal failing csv, I can debug and add a test case for this.  AFAIK, this works and its tested by *test-csv1*.  By column delimiter do you mean `*separator*`?  If you do not have any `*quote*` in the document you could set *quote* to some random unused character (perhaps `#\nul`) otherwise it expects  there to be quoted values.

Here is a test I wrote that shows this working:
```
(defparameter +test-tab-csv-issue-10+ "id	inches	name
1	72\"	Russ Tyndall
2	67\"	Amy Bobanolis
")

(define-test issue-10-tab-csv (:tags '(parsing bugs whitespace empty-line))
  (let* ((csv (read-csv +test-tab-csv-issue-10+ :quote #\nul :separator #\tab))
         (row1 (second csv)))
    (assert-equal "72\"" (second row1) csv)))
```

**Comment by analyticd** [comment]
Thanks! :quote #\nul did the trick
