### ISSUE TITLE
ACL regressions on quicklisp 2014-01-13

### ISSUE THREAD

**Issue by cl-test-grid** [AccelerationNet/cl-csv#16]
Hello.

cl-csv in quicklisp 2014-01-13 fails to build on ACL versions
where it was building OK previously.

The error is " Attempt to take the value of the unbound variable `ITERATE::_LOOP-STEP_' "

See test results of cl-csv on the last two quicklisp versions:
http://common-lisp.net/project/cl-test-grid/library/cl-csv.html
Clicking the error status in this report opens the build log.

**Comment by bobbysmith007** [comment]
Alright, I managed to figure out why ACL was complaining (finally years later).  Iterate clauses with a handler/restart were failing to have a variable bound (seemingly only on ACL).  I modified the code and was able to compile on ACL. 

Thanks again for the bug report
