### ISSUE TITLE
Parse failure (SB-KERNEL::HEAP-EXHAUSTED-ERROR)

### ISSUE THREAD

**Issue by dimitri** [AccelerationNet/cl-csv#18]
Given the CSV content from https://github.com/dimitri/pgloader/issues/123 and the test case embedded here I reproduce a heap exhaustion at each try. I began reading the code in cl-csv to attempt to fix it but I'm quite lost in there now...

```lisp
CL-USER> (with-open-file (input "/Users/dim/dev/temp/bug.csv" :direction :input :external-format :utf-8)
           (cl-csv:read-csv-row input :separator #\, :escape "\"\""))
; Evaluation aborted on #<SB-KERNEL::HEAP-EXHAUSTED-ERROR {1002C08053}>.
```

The input file content:

```
2014-11-07 10:02:17.302 CST,"gdt_new","gdt_insight_new",18445,"10.136.165.93:39143",545c1a19.480d,1,"COPY",2014-11-07 09:02:17 CST,6/1303255,1197337058,ERROR,57014,"canceling statement due to statement timeout",,,,,,"COPY (select t1.fspace, t3.fname, fad_target_classid, t2.name, num_client, num_client_big_imp, coverage 
from 
abc

order by t1.fspace, t1.fad_target_classid) TO STDOUT DELIMITER ',' NULL 'null' CSV QUOTE '""'",,"ProcessInterrupts, postgres.c:3314","psql"

```

Beware that there's an empty line in between abc and order by, which might get eaten by github.

**Comment by bobbysmith007** [comment]
Thanks for the detailed bug report.  I will look into it when I get a moment

**Comment by bobbysmith007** [comment]
I think this should resolve the problem, though I am slightly nervous, but all the tests pass.  Please verify your suite does as well.  Cheers

**Comment by dimitri** [comment]
My test suite pass too, and the bug report self-contained test that used to fail now pass too. It's a fix with no known regression for me, thanks very much!
