### ISSUE TITLE
Value-mapping function

### ISSUE THREAD

**Issue by mtstickney** [AccelerationNet/cl-csv#20]
Some applications have peculiar rules about how values are to be interpreted, particularly for null fields. For example, we have csv exports here where a null field is the string `"?"`, but only when it's unquoted.

In order to support strange requirements like that, it seems like `read-csv` could use a `:field-fn` argument, analogous to `:map-fn`, that takes two arguments and returns the value to be used as the field value in the row. The function should take the string that was parsed for the field, and a boolean indicating whether the string was quoted or unquoted.

There are some API-design considerations here (which is why this isn't a PR), mostly because this is a superset of the option to use the empty string as the null value. For backwards-compatibility I'd suggest making that option apply to a default function used for field mapping.

There's also the question of how this should play with the signals-based filtering facility (i.e. should signal filtering be done on the value before being passed to the mapping function, or on the value returned by it?).
I'd be happy to hear thoughts on that or any other issues with the idea.

**Comment by bobbysmith007** [comment]
Sorry, I somehow missed this question and its depth probably had me off thinking and I never came back.  Fundamentally I like this idea, and its pretty much implemented at the signals level, so adding a functional interface is probably not too difficult either. I recently set about rewriting this to make it a bit more reasonable to work on and so now am back checking all these issues.

Sorry again for the long delay

**Comment by bobbysmith007** [comment]
Version 1.0.1 has this feature. 

I ordered it : signals, then functions.
I pass the csv-reader (a new state object about the csv-parse) It contains all the possible information about the current parse (including weather we read a quoted value or not)

Cheers, and thanks for the input
