### ISSUE TITLE
several spaces as separater

### ISSUE THREAD

**Issue by crf1989** [AccelerationNet/cl-csv#24]
Hello,

If the data are separeted by several spaces rather than a tab, like "1#\space#\space2#\space#\space3",
is it a way to read the file properly? 

I tried to set :separater as #\space but that would give something like ("1" "" "2" "" "3").

Thank you.

**Comment by bobbysmith007** [comment]
Well drat... It supports multi-character line endings but not multi-character separators currently.  I look into this.

**Comment by bobbysmith007** [comment]
Also patches are accepted, but this is fairly optimized (eg: difficult to change) code

**Comment by bobbysmith007** [comment]
You could also write a row function that transforms the output by removing the required number of spaces from the result rows, but that is also kind of cludgy.

**Comment by crf1989** [comment]
I guess it's better not to change the code, and I shall try a row function or some other way.
Thanks for the reply!

**Comment by bobbysmith007** [comment]
Ok, well your ticket along with one recently about more flexible line endings had me have a go at rewriting the parser.  

Without using any tricks or optimizations, but with a more interesting design choice I was able to both improve readability, reduce interdependencies and closed variables, as well as improve performance slightly (not sure how I arranged that!).  

While its not quite where I want it to be, it is far enough along and seems to be passing the test suite well enough, that you may wish to check it out.  I will be pushing it up here momentarily.

**Comment by bobbysmith007** [comment]
version 1.0.1 should now be up
