### ISSUE TITLE
Parsing quote-escaped quotes

### ISSUE THREAD

**Issue by dimitri** [AccelerationNet/cl-csv#27]
From pgloader regression tests, we have cases where CL-CSV used to “just work” for us and where it's no longer the case. For instance the following used to be accepted input and is now failing with a new error:
```
(cl-csv:read-csv "2918,\"\"\"?\"\"\",\"Lost, Season 2\",Protected MPEG-4 video file,TV Shows,,2782333,528227089,1.99" :separator #\, :quote #\" :escape "\"\"" :escape-mode :quote)
```

```
non whitespace after quoted data #<CSV-READER LINE-IDX:0 CHARACTER-LINE-IDX:9 CHARACTER-IDX:9 "" {100A4FA733}> ?
   [Condition of type CL-CSV:CSV-PARSE-ERROR]
```

I'm not sure how to fix this one, so opening an issue here.

Some more of the raw content:

```
2917,The Greater Good,"Lost, Season 1",Protected MPEG-4 video file,TV Shows,,2617784,214130273,1.99
2918,"""?""","Lost, Season 2",Protected MPEG-4 video file,TV Shows,,2782333,528227089,1.99
2919,Born to Run,"Lost, Season 1",Protected MPEG-4 video file,TV Shows,,2618619,213772057,1.99
```

And a link to the whole file if you want to play with it: https://github.com/dimitri/pgloader/blob/master/test/data/track.csv.

**Comment by bobbysmith007** [comment]
I think this should all be fixed now.  Thanks for the bug report
