### ISSUE TITLE
Feature Request: ReadMe Sample Code Addition: How to read in a single specified row from csv

### ISSUE THREAD

**Issue by hardkase** [AccelerationNet/cl-csv#28]
Having looked at the readme and the documentation, reddit, stackoverflow, and the internet-at-large, I still can't wrap my head around how to read a single specified row from CSV. The following gets me row 1:

(cl-csv:read-csv-row #P[filename])

I can't figure out how to pass the desired row number into this function given the documentation. I'm sure it's a logic error on my part. A quick bit of sample code added to the readme would be fantastic. Thanks!

**Comment by bobbysmith007** [comment]
I don't think there is a function call to do that directly.

I would probably write something like:
```
(iter (for row in-csv #P"path") 
      (for i from 0) 
      (when (= i N)
        (return row)))
```
Or if you have a distaste for iterate:
```
(cl-csv::with-csv-input-stream (str #P"path") 
     (let ( row )
       (dotimes (i N row) 
          (setf row (cl-csv:read-csv-row str))))
```

This doesn't seem like a particularly common use case  (cursoring through a csv to a specific row), why are you doing that?  I dont mind adding a function to do that if there is a compelling reason, but its never been needed up till now, so I was curious.

**Comment by bobbysmith007** [comment]
Didnt mean to close it yet, sorry

**Comment by hardkase** [comment]
Hi Russ,


Thanks so much for your help. Will start testing your suggestions asap.

This is for a common lisp neural net using the MNIST dataset, and I'm using a CSV of pixel data values instead of the images. So for each run of the NN, I want to pull the next row of data as a list and run it through the network.


I hope this makes sense. I'm a lisp novice, and fairly clueless. If you need any follow up information, let me know, but I suspect one of your solutions will do the trick.


Thanks again!


Kind regards,


Patrick Collins

4th Year Computing in Games Development Student - Dundalk Institute of Technology

________________________________

**Comment by hardkase** [comment]
The second option should work, but I get a resolvable issue with "You are in the top-level Read-Eval-Print loop."

Again, I'm sure this is a noob mistake, but is there a flag or parameter I need to use to avoid this? Screenshot attached.


Thanks a million.


Regards,

Patrick Collins[cid:cc07a07a-79f1-4562-bf7b-c4abb971fdc6]

________________________________

**Comment by hardkase** [comment]
I'm using GNU clisp on windows 10. Testing on a tiny subsection of the actual training data which is 785 cells by 60000 rows,  using 15 row csv, this code results in the messaging pictured, but it does print the correct row to console on entering :h. If there's a way to silence this messaging, that would be really helpful. If it's not in your scope, I totally get it. You've given me a huge boost with this project as it is. I've been beating my head against this for 2 days, so I really appreciate the help.


________________________________

**Comment by bobbysmith007** [comment]
Sorry, I dont have windows or clisp, so I am unlikely to be able to help much there (I didnt get a screen shot if you tried to send one).  If you do attach one on the ticket at github, or copy / paste the stacktrace / console, I might be able to spot something.

**Comment by hardkase** [comment]
![clisp-issue](https://user-images.githubusercontent.com/10947216/38836977-2c80c350-41c8-11e8-8b07-b1c64a6313cf.png)

**Comment by bobbysmith007** [comment]
I installed CLISP, and that message only shows up for me if I type `:h` into the shell.  It doesnt seem like a side effect of cl-csv, but rather of your usage of CLISP (ie: you seem to have included `:h` into the forms)

**Comment by bobbysmith007** [comment]
I'm leaving for the day, but will check back tomorrow.  Good luck 👍

**Comment by hardkase** [comment]
Thanks again so much for your help!

**Comment by bobbysmith007** [comment]
Did you get it figured out?
