### ISSUE TITLE
cl-csv ppears to be deleting, rather than doubling, internal quotes on write

### ISSUE THREAD

**Issue by dfmorrison** [AccelerationNet/cl-csv#29]
Latest cl-csv available on Quicklisp, `cl-csv-20180228-git`.
Running in SBCL 1.4.7 on 64-bit Ubuntu 18.04.
This is with out of the box settings for cl-csv.

```
DFM> (cl-csv:write-csv '(("Foo \"quoted\" bar")) :stream *standard-output*)
"Foo quoted bar"
NIL
DFM>

```
I believe this should actually be printing

`"Foo ""quoted"" bar"`

Reading a value such as `"Foo ""quoted"" bar"` seems to work fine.

**Comment by bobbysmith007** [comment]
That definitely seems like bug, though I was fairly sure we had a test case for that.  I will definitely look into this.  Thanks for the bug report  :+1:

**Comment by bobbysmith007** [comment]
This seems to be about the value of the special variable *quote-escape* - it defaults to nil (which is the the change that caused the bug).    It used to default to `""` but that changed recently (last yearish) when I updated the parser.  You can work around this by explicitly setting this, when writing, to whatever escape system you want.  I have changed the default in `write-csv-value` to write double-double-quotes if no escape is set.

Thanks!

**Comment by bobbysmith007** [comment]
Hope this solves your issue.  Have a good one

**Comment by dfmorrison** [comment]
On Thu, Jul 12, 2018 at 4:11 PM Russ Tyndall <notifications@github.com>
wrote:
> This seems to be about the value of the special variable
> quote-escape - it defaults to nil (which is the the change that
> caused the bug). It used to default to "" but that changed recently
> (last yearish) when I updated the parser. You can work around this
> by explicitly setting this, when writing, to whatever escape system
> you want.
​​
Confirming that this seems to fix things for me. Thanks!


DFM> (cl-csv:write-csv '(("Foo \"quoted\" bar")) :stream *standard-output*
:escape "\"\"")
"Foo ""quoted"" bar"
NIL
DFM> (setf cl-csv:*quote-escape* "\"\"")
"\"\""
DFM> (cl-csv:write-csv '(("Foo \"quoted\" bar")) :stream *standard-output*)
"Foo ""quoted"" bar"
NIL
DFM>



-- 
Don Morrison <dfm2@cmu.edu>
“When my son was eight months old, it could truthfully be said that he
devoured literature....He was, of course, not the first child to indulge
in bibliophagy. The great Philadelphia bookdealer A.S.W. Rosenbach deduced
that one reason first editions of /Alice in Wonderland/ were so scarce
was that so many of them had been eaten.”     — Anne Fadiman, /Ex Libris/
