### ISSUE TITLE
Suggestion: use a reader macro

### ISSUE THREAD

**Issue by equwal** [AccelerationNet/cl-csv#36]
There is an implementation of this in my CSV repository:
https://github.com/equwal/CSV/blob/f122dd6eeb0eb3a971ae7b02bb3c9abc9c073c51/csv.lisp#L47

**Comment by bobbysmith007** [comment]
Howdy @equwal 

STD Disclaimer:  I don't actively use LISP much anymore, and its unlikely that I would ever get around to implementing this.   I *might* be able to merge a patch with tests.  

Fundamentally though, I am not much interested in directly reading CSV from a lisp file using a reader macro...  I use reader macros occasionally (regex, string interpolation and sometimes cl-sql), but all of these are trying to over lay a meaningful syntax inside my lisp environment, where-as out side of the test suite for CL-CSV, I doubt I would ever wish to embed a CSV directly in a lisp document.  

Your csv library seems like a good place to learn your way around lisp.  I'ld like to wish you luck and fortune on your lisp journey.  Lisp is where I learned the most, but python is probably where I get the most done, while php is where I actually get paid the most.
