### ISSUE TITLE
Does not build with 2.0.9 - slot :initform/:type issue

### ISSUE THREAD

**Issue by quicklisp** [AccelerationNet/cl-csv#41]
Log here: http://report.quicklisp.org/2020-09-28/failure-report/cl-csv.html#cl-csv

SBCL 2.0.9 does stricter checking when `:initform` is NIL and does not match the `:type` option.

**Comment by bobbysmith007** [comment]
I believe @slyrus got this fixed AccelerationNet/cl-csv/pull/42

**Comment by quicklisp** [comment]
Looks good to me, thanks!
