### ISSUE TITLE
Attempting to iterate on two CSV files in parallel signals an error

### ISSUE THREAD

**Issue by dfmorrison** [AccelerationNet/cl-csv#43]
This is cl-csv version 1.0.6, running in SBCL version 2.0.10, on Ubuntu Linux 20.04, on an Intel machine.

With the attached CSV files, running

```
(iter (for (x y) in-csv #P"numbers.csv")
      (for (u v) in-csv #P"letters.csv")
      (collect (list x u y v)))
```

results in the following error

```
Iterate, in (WITH *SEPARATOR* = (OR NIL *SEPARATOR*)):
Duplicate variable: *SEPARATOR*
   [Condition of type SIMPLE-ERROR]
```

[numbers.csv](https://github.com/AccelerationNet/cl-csv/files/6353799/numbers.csv)
[letters.csv](https://github.com/AccelerationNet/cl-csv/files/6353800/letters.csv)

**Comment by bobbysmith007** [comment]
Thank you for reporting this bug!

I'ld love to get to this, but I havent booted up lisp in a year or so.  I will accept / merge patches and am open to other maintainers.

**Comment by bobbysmith007** [comment]
It is likely that I should be using a let block instead of a with-block clause
